Events_Management/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include # new
urlpatterns = [
path('admin/', admin.site.urls),
path('', include('events.urls')), # new
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


from .views import (
    HomeListView,
    SpeakerListView,
    ScheduleListView,
    ParticipantListView,
    SpeakerDetailsListView,
    EventListView,
    RegisterListView,
    EventDetailsListView,
)

urlpatterns = [
    path("", HomeListView.as_view(), name="home"),
    path("speaker/", SpeakerListView.as_view(), name="speaker"),
    path("speaker/<int:pk>/", SpeakerDetailsListView.as_view(), name="speaker_details"),
    path("schedule/", ScheduleListView.as_view(), name="schedule"),
    # path('schedule/<int:pk>/', ScheduleDetailsListView.as_view(), name='schedule_details'),
    path("participants/", ParticipantListView.as_view(), name="participant"),
    # path('participants/<int:pk>/', ParticipantDetailsListView.as_view(), name='participant_details'),
    path("event/", EventListView.as_view(), name="event_list"),
    path("event/<int:pk>/", EventDetailsListView.as_view(), name="event_details"),
    path("purchase/", SpeakerListView.as_view(), name="purchase"),
    path("/register", RegisterListView.as_view(), name="register"),
]

events/models.py
from django.db import models


class EventList(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateTimeField()
    category = models.CharField(
        max_length=50,
        choices=(
            ("MUSIC", "Music"),
            ("SPORTS", "Sports"),
            ("SCIENCE", "Science"),
            ("TECHNOLOGY", "Technology"),
        ),
        default="FREE",
    )
    payment = models.CharField(
        max_length=4, choices=(("FREE", "Free"), ("PAID", "Paid")), default="FREE"
    )
    detail = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    location = models.CharField(max_length=200)
    category = models.CharField(
        max_length=50,
        choices=(
            ("MUSIC", "Music"),
            ("SPORTS", "Sports"),
            ("SCIENCE", "Science"),
            ("TECHNOLOGY", "Technology"),
        ),
        default="FREE",
    )
    event_access = models.CharField(
        max_length=4, choices=(("FREE", "Free"), ("PAID", "Paid")), default="FREE"
    )

    def __str__(self):
        return self.title


class Speaker(models.Model):
    name = models.CharField(max_length=100)
    biography = models.TextField()
    photo = models.ImageField(upload_to="images/")
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    linkedin_link = models.URLField()
    twitter_link = models.URLField()

    def __str__(self):
        return self.name


class EventDetail(models.Model):
    name = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    attended = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    shifts = models.CharField(max_length=100)
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Schedule(models.Model):
    category_title = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    day = models.CharField(max_length=10)
    date = models.DateTimeField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    speaker_name = models.CharField(max_length=100)

    def __str__(self):
        return self.topic


class Participant(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    event = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Register(models.Model):
    def __str__(self):
        return self


class SpeakerDetail(models.Model):
    name = models.CharField(max_length=100)
    biography = models.TextField()
    photo = models.ImageField(upload_to="images/")
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    linkedin_link = models.URLField()
    twitter_link = models.URLField()
    event_1 = models.CharField(max_length=100, null=True)
    event_2 = models.CharField(max_length=100, null=True)
    event_3 = models.CharField(max_length=100, null=True)
    rating = models.CharField(max_length=10, null=True)

    def __str__(self):
        return self.name

events/views.py
from django.views.generic import ListView
from .models import (
    Event,
    Speaker,
    Schedule,
    Participant,
    SpeakerDetail,
    EventList,
    Register,
    EventDetail,
)


class HomeListView(ListView):
    model = Event
    template_name = "home.html"


class RegisterListView(ListView):
    model = Register
    template_name = "register.html"


class SpeakerListView(ListView):
    model = Speaker
    template_name = "speaker.html"


class ScheduleListView(ListView):
    model = Schedule
    template_name = "schedule.html"


class ParticipantListView(ListView):
    model = Participant
    template_name = "participants.html"


class EventListView(ListView):
    model = EventList
    template_name = "event.html"


class SpeakerDetailsListView(ListView):
    model = SpeakerDetail
    template_name = "speaker_details.html"


class EventDetailsListView(ListView):
    model = EventDetail
    template_name = "event_details.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kiny">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Manup Template">
    <meta name="keywords" content="Manup, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>💫VConfus | Conference Platform</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">
    <!-- animations cdn css  -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <!-- Css Styles and Bootstrap Custom -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo">
                <a href="{% url 'home' %}">
                    <p style="font-size: 40px;font-weight: bold;color: purple;">💫VConfus</p>
                </a>
            </div>
            <div class="nav-menu">
                <nav class="mainmenu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'speaker' %}">Speakers</a>
                            <ul class="dropdown">
                                {% for info in speaker_list %}
                                <li><a href="{% url 'speaker_details' info.pk %}">{{ info.name }}</a></li>
                                {% endfor %} 
                            </ul>
                        </li>
                       <li><a href="{% url 'schedule' %}">Schedule</a></li>
                       <li><a href="{% url 'participant' %}">Participants</a></li>
                    <li><a href="{% url 'event_list' %}">Events</a></li>
                    </ul>
                </nav>
                <a href="{% url 'register' %}" class="primary-btn top-btn rounded-1">Register</a>
            </div> 
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->
    {% block content %}
    {% endblock content %}

     <!-- Footer Section Begin -->
     <footer class="footer-section">
        <div class="container">
            <div class="partner-logo owl-carousel">
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="{% static 'img/partner-logo/logo-1.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="{% static 'img/partner-logo/logo-2.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="{% static 'img/partner-logo/logo-3.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="{% static 'img/partner-logo/logo-4.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="{% static 'img/partner-logo/logo-6.png' %}" alt="">
                    </div>
                </a>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-text">
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Speakers</a></li>
                            <li><a href="#">Schedule</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                        <div class="copyright-text"><p>
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved</div>
                        <div class="ft-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

      <!-- animation initializer start  -->
      <script>
        AOS.init();
      </script>
      <!-- animation initializer end -->

     <!-- animation cdn js  -->
     <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/event.html
{% extends 'base.html' %}
{% load static %}


 {% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section">
   <div class="container">
     <div class="row">
        <div class="col-lg-12">
          <div class="breadcrumb-text">
              <h2>Event List</h2>
              <div class="bt-option">
                  <a href="{% url 'home' %}">Home</a>
                  <span>Our Event List</span>
                </div>
            </div>
         </div>
      </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Schedule Table Section Begin -->
<section class="schedule-table-section spad">
<div class="container">
  <div class="row">
      <div class="col-lg-12">
          <div class="schedule-table-tab">
              <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item">
                      <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Names</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab">Date</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tabs-5" role="tab">Category</a>
                  </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#tabs-5" role="tab">Payment Status</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#tabs-5" role="tab">Details</a>
            </li>

              </ul><!-- Tab panes -->
              {% for info in eventlist_list %}
              <div class="tab-content">
                  <div class="tab-pane active" id="tabs-1" role="tabpanel">
                      <div class="schedule-table-content">
                          <table>
                              <tbody>
                                  <tr>
                                    <td class="break hover-bg">
                                        <h5>{{ info.name }}</h5>
                                    </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.date }}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.category }}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.payment }}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                        <h5><a href="{% url 'event_details' info.pk %}">{{ info.detail }}</a></h5>
                                    </td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
            {% endfor %}  
          </div>
      </div> 
  </div>
</div>
</section>
<!-- Schedule Table Section End -->

{% endblock content %}

templates/event_details.html
{% extends 'base.html' %}
{% load static %}


 {% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section">
   <div class="container">
     <div class="row">
        <div class="col-lg-12">
          <div class="breadcrumb-text">
              <h2>Event Details</h2>
              <div class="bt-option">
                  <a href="{% url 'home' %}">Home</a>
                  <span>Our Event Details</span>
                </div>
            </div>
         </div>
      </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Schedule Table Section Begin -->
<section class="schedule-table-section spad">
<div class="container">
  <div class="row">
      <div class="col-lg-12">
          <div class="schedule-table-tab">
              <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item">
                      <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Amount</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab">Paricipant Attended</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tabs-5" role="tab">Location</a>
                  </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#tabs-5" role="tab">Payment Status</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#tabs-5" role="tab">Shifts</a>
            </li>

              </ul><!-- Tab panes -->
              {% for info in eventdetail_list %}
              <div class="tab-content">
                  <div class="tab-pane active" id="tabs-1" role="tabpanel">
                      <div class="schedule-table-content">
                          <table>
                              <tbody>
                                  <tr>
                                    <td class="break hover-bg">
                                        <h5>{{ info.amount }}</h5>
                                    </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.attended }}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.location}}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.status }}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                        <h5>{{ info.shifts }}</h5>
                                    </td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
            {% endfor %}  
          </div>
      </div> 
  </div>
</div>
</section>
<!-- Schedule Table Section End -->

{% endblock content %}

templates/participants.html
{% extends 'base.html' %}
{% load static %}


 {% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section">
   <div class="container">
     <div class="row">
        <div class="col-lg-12">
          <div class="breadcrumb-text">
              <h2>PARTICIPANTS</h2>
              <div class="bt-option">
                  <a href="{% url 'home' %}">Home</a>
                  <span>Our Participants</span>
                </div>
            </div>
         </div>
      </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Schedule Table Section Begin -->
<section class="schedule-table-section spad">
<div class="container">
  <div class="row">
      <div class="col-lg-12">
          <div class="schedule-table-tab">
              <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item">
                      <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Names</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab">Email</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab">Phone Number</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tabs-5" role="tab">Event</a>
                  </li>
              </ul><!-- Tab panes -->
              {% for info in participant_list %}
              <div class="tab-content">
                  <div class="tab-pane active" id="tabs-1" role="tabpanel">
                      <div class="schedule-table-content">
                          <table>
                              <tbody>
                                  <tr>
                                    <td class="break hover-bg">
                                        <h5>{{ info.name }}</h5>
                                    </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.email }}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.phone_number }}</h5>
                                      </td>
                                      <td class="break hover-bg">
                                          <h5>{{ info.event }}</h5>
                                      </td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
            {% endfor %} 
          </div>
      </div> 
  </div>
</div>
</section>
<!-- Schedule Table Section End -->

{% endblock content %}

templates/schedule.html
     {% extends 'base.html' %}
      {% load static %}


       {% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section">
         <div class="container">
           <div class="row">
              <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>SCHEDULE</h2>
                    <div class="bt-option">
                        <a href="{% url 'home' %}">Home</a>
                        <span>Our Schedules</span>
                      </div>
                  </div>
               </div>
            </div>
          </div>
    </section>
<!-- Breadcrumb Section End -->
  
  <!-- Schedule Table Section Begin -->
  <section class="schedule-table-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="schedule-table-tab">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Technology</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Marketing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Industry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Tourism</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Architecture</a>
                        </li>
                    </ul><!-- Tab panes -->
                    {% for info in schedule_list %}
                    <div class="tab-content">
                        <div class="tab-pane active" id="tabs-1" role="tabpanel">
                            <div class="schedule-table-content">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>
                                                    <strong>Start - End Date</strong>
                                            </th>
                                            <th>
                                                <strong>Day {{ info.day}}</strong>
                                                <span>{{ info.date}}</span>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="event-time">{{ info.start_time}} - {{ info.end_time}}</td>
                                            <td class="hover-bg">
                                                <h5>{{ info.topic }}</h5>
                                                <p><span>By </span>{{ info.speaker_name }}</p>
                                            </td> 
                                    </tbody>
                                  </table>
                              </div> 
                           </div>
                         </tbody>
                       </table>
                    </div>
                    {% endfor %} 
                  </div>
               </div>
            </div>
        </div>
    </div>
    </div>
</section>
<!-- Schedule Table Section End -->
 
{% endblock content %}

templates/speaker.html
   {% extends 'base.html' %}
   {% load static %}


     {% block content %}
     
 <!-- Breadcrumb Section Begin -->
 <section class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Speakers</h2>
                    <div class="bt-option">
                        <a href="{% url 'home' %}">Home</a>
                        <span>Our Speakers</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Speaker Section Begin --> 
<section class="speaker-section spad">
    <div class="container">
        <div class="row">
            {% for info in speaker_list %}
            <div class="col-sm-6">
                <div class="speaker-item">
                    <div class="row">  
                        <div class="col-lg-6">
                            <div class="si-pic">
                                <img src="{{ info.photo.url}}" alt="">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="si-text">
                                <div class="si-title">
                                    <h4><a href="{% url 'speaker_details' info.pk %}" style="text-decoration: none;color: black;"> {{ info.name }}</a></h4>
                                    <span>Email: {{ info.email }}</span>
                                    <span style="color: black;font-weight: bold;">Phone: {{ info.phone_number }}</span>
                                </div>
                                <div class="si-social">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-google-plus"></i></a>
                                </div>
                                <p>{{ info.biography }}</p>
                            </div>
                        </div>
                    </div>
                </div>
           </div> 
           {% endfor %}  
        <div class="load-more">
            <a href="#" class="primary-btn">Load More</a>
        </div>
    </div>
</section>
<!-- Speaker Section End -->

  {% endblock content %}

templates/speaker_details.html
{% extends 'base.html' %}
{% load static %}


 {% block content %}

 {% for info in speakerdetail_list %}
<!-- Home About Section Begin -->
<section class="home-about-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="ha-pic">
                    <img src="{{ info.photo.url}}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="ha-text">
                    <h2>{{ info.name }}</h2>
                    <p>{{ info.biography }}</p>
                    <ul>
                        <li><span class="icon_check"></span> {{ info.event_1 }}</li>
                        <li><span class="icon_check"></span> {{ info.event_2 }}</li>
                        <li><span class="icon_check"></span> {{ info.event_3 }}</li>
                        <li><span class="fa fa-twitter"></span> {{ info.twitter_link }}</li>
                        <li><span class="fa fa-facebook"></span> {{ info.linkedin_link }}</li>
                        <li><span class="icon_phone"></span> {{ info.phone_number }}</li>
                        <div style="display: flex;gap: 4px;">
                            <li><span class="fa fa-star"></span></li>
                            <li><span class="fa fa-star"></span></li>
                            <li><span class="fa fa-star"></span></li>
                            <li><span class="fa fa-star"></span></li>
                        </div>
                    </ul>
                    <a href="" class="ha-btn">Discover Now</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}  
</section>
<!-- Home About Section End -->

{% endblock content %}